version: 0.0
# Specify "os: linux" if this revision targets Amazon Linux
os: linux

files:
  - source: /
    destination: /var/www/html

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
